#%RAML 1.0
---
uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

title: Property Business (MTD)
description: List, create, retrieve and amend Foreign Property Income & Expenditure Period Summaries and retrieve, amend and delete Foreign Property Annual Submissions.
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Send fraud prevention data
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/fraud-prevention.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

'/individuals/business/property':
  /uk:
    /{nino}:
      uriParameters:
        nino:
          description: National Insurance number, in the format AA999999A.
          type: string
          example: TC663795B
      /{businessId}:
        uriParameters:
          businessId:
            description: 'An identifier for the business, unique to the customer.<p>Must conform to the regular expression `^X[A-Z0-9]{1}IS[0-9]{11}$`'
            example: XAIS12345678910
        /annual:
          (annotations.group):
            name: UK Property Business Annual Submission
            description: Resources relating to an individual's UK Property Business Annual Submission
          /{taxYear}:
            uriParameters:
              taxYear:
                description: 'The tax year to which the data applies. For example: 2022-23. The start year and end year must not span two tax years. The minimum tax year is 2022-23. No gaps are allowed, for example, 2022-24 is not valid. (The minimum tax year in Sandbox is 2021-22.)'
                example: 2022-23
            get: !include uk_property_annual_submission_retrieve.raml
            put: !include uk_property_annual_submission_create_and_amend.raml
        /period:
          (annotations.group):
            name: UK Property Income & Expenses Period Summary
            description: Resources relating to an individual's UK Property Income & Expenses Period Summary
          /{taxYear}:
            uriParameters:
              taxYear:
                description: 'The tax year to which the data applies. For example, 2022-23. The start year and end year must not span two tax years. The minimum tax year is 2022-23. No gaps are allowed, for example, 2022-24 is not valid. (The minimum tax year in Sandbox is 2021-22.)'
                example: 2022-23
            post: !include uk_property_period_summary_create.raml
            /{submissionId}:
              uriParameters:
                submissionId:
                  description: 'An identifier for the income and expenditure period summary.<p>Must conform to the regular expression `^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
                  example: 4557ecb5-fd32-48cc-81f5-e6acd1099f3c
              get: !include uk_property_period_summary_retrieve.raml
              put: !include uk_property_period_summary_amend.raml
    /annual:
      /furnished-holiday-lettings:
        /{nino}:
          (annotations.group):
            name: Historic FHL UK Property Income & Expenses Period Summary
            description: Resources relating to an individual's historic FHL UK Property Income & Expenses Period Summaries.
          uriParameters:
            nino:
              description: National Insurance number, in the format AA999999A.
              type: string
              example: TC663795B
          /{taxYear}:
            (annotations.group):
              name: Historic FHL UK Property Business Annual Submission
              description: Resources relating to an individual's historic FHL UK Property Business Annual Submission
            uriParameters:
              taxYear:
                description: 'The tax year to which the data applies. For example: 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2017-18 and the maximum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid. (The minimum tax year in Sandbox is 2021-22.)'
                example: 2021-22
            delete: !include historic_uk_fhl_annual_submission_delete.raml
    /furnished-holiday-lettings:
      /{nino}:
        (annotations.group):
          name: Historic FHL UK Property Income & Expenses Period Summary
          description: Resources relating to an individual's historic FHL UK Property Income & Expenses Period Summaries.
        uriParameters:
          nino:
            description: National Insurance number, in the format AA999999A.
            type: string
            example: TC663795B
        post: !include historic_uk_fhl_period_summary_create.raml
        /{periodId}:
          uriParameters:
            periodId:
              description: An identifier for the update period, unique to the customer's UK property business.
              type: string
              example: 2017-04-06_2017-07-04
          put: !include historic_uk_fhl_period_summary_amend.raml
        /{taxYear}:
          (annotations.group):
            name: Historic FHL UK Property Business Annual Submission
            description: Resources relating to an individual's historic FHL UK Property Business Annual Submission
          uriParameters:
            taxYear:
              description: 'The tax year to which the data applies. For example: 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2017-18 and the maximum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid. (The minimum tax year in Sandbox is 2021-22.)'
              example: 2021-22
          put: !include historic_uk_fhl_annual_submission_create_and_amend.raml
          get: !include historic_uk_fhl_annual_submission_retrieve.raml
    /non-furnished-holiday-lettings:
      /{nino}:
        (annotations.group):
          name: Historic non-FHL UK Property Income & Expenses Period Summary
          description: Resources relating to an individual's historic non-FHL UK Property Income & Expenses Period Summaries.
        uriParameters:
          nino:
            description: National Insurance number, in the format AA999999A.
            type: string
            example: TC663795B
        post: !include historic_uk_non_fhl_period_summary_create.raml
        /{taxYear}:
          (annotations.group):
            name: Historic non-FHL UK Property Business Annual Submission
            description: Resources relating to an individual's historic non-FHL UK Property Business Annual Submission
          uriParameters:
            taxYear:
              description: 'The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2017-18 and the maximum tax year is 2021-22. No gaps are allowed, for example, 2020-22 is not valid.'
              example: 2021-22
          get: !include historic_uk_non_fhl_annual_submission_retrieve.raml
          delete: !include historic_uk_non_fhl_annual_submission_delete.raml
  /foreign:
    /{nino}:
      uriParameters:
        nino:
          description: National Insurance number, in the format AA999999A.
          type: string
          example: TC663795B
      /{businessId}:
        uriParameters:
          businessId:
            description: 'An identifier for the business, unique to the customer. <p>Must conform to the regular expression `^X[A-Z0-9]{1}IS[0-9]{11}$`'
            example: XAIS12345678910
        /period:
          (annotations.group):
            name: Foreign Property Income & Expenses Period Summary
            description: Resources relating to an individual's Foreign Property Income & Expenses Period Summary
          /{taxYear}:
            uriParameters:
              taxYear:
                description: 'The tax year to which the data applies. For example, 2022-23.  The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid.'
                example: 2022-23
            post: !include foreign_property_period_summary_create.raml
            /{submissionId}:
              uriParameters:
                submissionId:
                  description: 'An identifier for the income and expenses period summary. <p>Must conform to the regular expression `^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`'
                  example: 4557ecb5-fd32-48cc-81f5-e6acd1099f3c
              get: !include foreign_property_period_summary_retrieve.raml
              put: !include foreign_property_period_summary_amend.raml
        /annual:
          (annotations.group):
            name: Foreign Property Annual Submission
            description: Resources relating to an individual's Foreign Property Annual Submission
          /{taxYear}:
            uriParameters:
              taxYear:
                description: 'The tax year to which the data applies. For example: 2022-23. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid.'
                example: 2022-23
            put: !include foreign_property_annual_submission_create_and_amend.raml
            get: !include foreign_property_annual_submission_retrieve.raml
  /{nino}:
    uriParameters:
      nino:
        description: National Insurance number, in the format AA999999A.
        type: string
        example: TC663795B
    /{businessId}:
      uriParameters:
        businessId:
          description: 'An identifier for the business, unique to the customer.<p>Must conform to the regular expression `^X[A-Z0-9]{1}IS[0-9]{11}$`'
          example: XAIS12345678910
      /annual:
        (annotations.group):
          name: UK or Foreign Property Annual Submission Deletion
          description: Resources relating to an individual's UK or Foreign Property Annual Submission Deletion
        /{taxYear}:
          uriParameters:
            taxYear:
              description: 'The tax year to which the data applies. For example: 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid.'
              example: 2021-22
          delete: !include delete_property_submission.raml
      /period:
        (annotations.group):
          name: UK or Foreign Property Income and Expenses Period Summaries List
          description: Resources relating to an individual's UK or Foreign Property Income and Expenses Period Summaries List
        /{taxYear}:
          uriParameters:
            taxYear:
              description: 'The tax year to which the data applies. For example: 2022-23. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2022-24 is not valid.'
              example: 2022-23
          get: !include property_period_summaries_list.raml