is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBusinessId
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Delete a Property Annual Submission [test only]
description: This endpoint allows a developer to delete income and expenditure for a property business. For either or both of Furnished Holiday Letting (FHL) in the European Economic Area (EEA) and Non FHL property submissions. A National Insurance number, business ID and tax year are required.
(annotations.sandboxData): !include scenarios/delete_property_summary_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  204:
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.