#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
# 404
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: The supplied income source could not be found.
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  submissionIdNotFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              submissionIdNotFound:
                description: A submission with this Submission ID does not exist for this Business Income Source.
                value:
                  code: SUBMISSION_ID_NOT_FOUND
# 403
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
# 400
# FORMAT_XXX
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid.
                value:
                  code: FORMAT_NINO
  formatBusinessId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatBusinessId:
                description: The format of the supplied Business ID field is not valid.
                value:
                  code: FORMAT_BUSINESS_ID
  formatFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatFromDate:
                description: The format of the supplied From date field is not valid.
                value:
                  code: FORMAT_FROM_DATE
  formatToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatToDate:
                description: The format of the supplied To date field is not valid.
                value:
                  code: FORMAT_TO_DATE
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: The format of one or more monetary fields is not valid.
                value:
                  code: FORMAT_VALUE
  formatDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatDate:
                description: The supplied date format is not valid.
                value:
                  code: FORMAT_DATE
  formatString:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatString:
                description: One or more strings have been added with the incorrect format.
                value:
                  code: FORMAT_STRING
  formatSubmissionId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSubmissionId:
                description: The format of the supplied Submission ID field is not valid.
                value:
                  code: FORMAT_SUBMISSION_ID
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year field is not valid.
                value:
                  code: FORMAT_TAX_YEAR
  formatCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCountryCode:
                description: The format of the supplied Country Code field is not valid.
                value:
                  code: FORMAT_COUNTRY_CODE
# RULE_XXX
  ruleIncorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIncorrectOrEmptyBody:
                description: An empty or non-matching body was submitted.
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTypeOfBusinessIncorrect:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleTypeOfBusinessIncorrect:
                  description: The supplied Business ID does not represent a UK property business.
                  value:
                    code: RULE_TYPE_OF_BUSINESS_INCORRECT
  ruleToDateBeforeFromDate:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleToDateBeforeFromDate:
                  description: The To date is earlier than the From date.
                  value:
                    code: RULE_TO_DATE_BEFORE_FROM_DATE
  ruleTaxYearNotSupported:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleTaxYearNotSupported:
                  description: The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.
                  value:
                    code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                ruleTaxYearRangeInvalid:
                  description: Tax year range invalid. A tax year range of one year is required.
                  value:
                    code: RULE_TAX_YEAR_RANGE_INVALID
  ruleBothExpensesSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleBothExpensesSupplied:
                description: Both Expenses and Consolidated Expenses must not be present at the same time.
                value:
                  code: RULE_BOTH_EXPENSES_SUPPLIED
  ruleBothAllowancesSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleBothAllowancesSupplied:
                description: Both allowances and property income allowance must not be present at the same time.
                value:
                  code: RULE_BOTH_ALLOWANCES_SUPPLIED
  ruleBuildingNameNumber:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleBuildingNameNumber:
                description: One of building name or number must be supplied.
                value:
                  code: RULE_BUILDING_NAME_NUMBER
  ruleCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCountryCode:
                description: Not a valid ISO 3166-1 alpha-3 country code.
                value:
                  code: RULE_COUNTRY_CODE
  ruleOverlappingPeriod:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleOverlappingPeriod:
                description: Period summary overlaps with any of the existing period summaries.
                value:
                  code: RULE_OVERLAPPING_PERIOD
  ruleMisalignedPeriod:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleMisalignedPeriod:
                description: Period summary is not within the accounting period.
                value:
                  code: RULE_MISALIGNED_PERIOD
  ruleNotContiguousPeriod:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleNotContiguousPeriod:
                description: Period summaries are not contiguous.
                value:
                  code: RULE_NOT_CONTIGUOUS_PERIOD
  ruleDuplicateSubmission:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateSubmission:
                description: A summary has already been submitted for the period specified.
                value:
                  code: RULE_DUPLICATE_SUBMISSION
  ruleDuplicateCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDuplicateCountryCode:
                description: Duplicate Country code is not allowed.
                value:
                  code: RULE_DUPLICATE_COUNTRY_CODE
# MISSING_XXX
  missingFromDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingFromDate:
                description: The From date parameter is missing.
                value:
                  code: MISSING_FROM_DATE
  missingToDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              missingToDate:
                description: The To date parameter is missing.
                value:
                  code: MISSING_TO_DATE
