is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBusinessId
  - errors.formatSubmissionId
  - errors.ruleTypeOfBusinessIncorrectForeign
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Retrieve a Foreign Property Income & Expenses Period Summary [test only]
description: This endpoint allows a developer to retrieve the income and expenses for a Foreign Property business, using the submission ID for either or both of Furnished Holiday Lettings (FHL) in the European Economic Area (EEA) and all other Foreign Property submissions. A National Insurance number, business ID, and tax year are required.
(annotations.sandboxData): !include scenarios/foreign_property_period_summary_retrieve_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/foreign_property_period_summary_retrieve/response.json
        examples:
          example-1:
            description: Full Expenses response
            value: !include examples/foreign_property_period_summary_retrieve/response.json
          example-2:
            description: Consolidated Expenses response
            value: !include examples/foreign_property_period_summary_retrieve/consolidated_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.