is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBusinessId
  - errors.formatSubmissionId
  - errors.formatCountryCode
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.formatValue
  - errors.ruleBothExpensesSupplied
  - errors.ruleTypeOfBusinessIncorrect
  - errors.ruleDuplicateCountryCode
  - errors.ruleIncorrectOrEmptyBody
  - errors.ruleCountryCode
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Amend a Foreign Property Income & Expenses Period Summary
description: This endpoint allows a developer to re-submit the income and expenses for a foreign property business. This submission is for either or both of Furnished Holiday Letting (FHL) in the European Economic Area (EEA) and all other foreign property submissions. A National Insurance number, business ID, tax year and submission ID are required.
(annotations.sandboxData): !include scenarios/foreign_property_period_summary_amend_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/foreign_property_period_summary_amend/request.json
    examples:
      example-1:
        description: Full Expenditure request
        value: !include examples/foreign_property_period_summary_amend/request.json
      example-2:
        description: Consolidated Expenditure request
        value: !include examples/foreign_property_period_summary_amend/consolidated_request.json
responses:
  200:
    body:
      application/json:
        type: !include schemas/foreign_property_period_summary_amend/response.json
        examples:
          example:
            description: Example Response
            value: !include examples/foreign_property_period_summary_amend/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.