is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatValue
  - errors.formatFromDate
  - errors.formatToDate
  - errors.ruleToDateBeforeFromDate
  - errors.ruleBothExpensesSupplied
  - errors.ruleIncorrectOrEmptyBody
  - errors.ruleDuplicateSubmission
  - errors.ruleMisalignedPeriod
  - errors.ruleOverlappingPeriod
  - errors.ruleNotContiguousPeriod
  - errors.rulePeriodTaxYearNotSupported
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Create a Historic FHL UK Property Income & Expenses Period Summary
description: This endpoint enables you to create income and expenses for a furnished holiday lettings (FHL) UK property business and make periodic submissions for tax years from 2017-18 to 2021-22.  A National Insurance number must be provided. Use this endpoint only for the specified tax year range; for current tax year submissions, use the Retrieve a UK Property Income & Expenses Period Summary endpoint.
(annotations.sandboxData): !include scenarios/historic_uk_period_summary_create_scenarios.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
  application/json:
    type: !include schemas/historic_uk_fhl_period_summary_create/request.json
    examples:
      example-1:
        description: Full Expenses request
        value: !include examples/historic_uk_fhl_period_summary_create/request.json
      example-2:
        description: Consolidated Expenses request
        value: !include examples/historic_uk_fhl_period_summary_create/consolidated_request.json
responses:
  202:
    body:
      application/json:
        type: !include schemas/historic_uk_fhl_period_summary_create/response.json
        examples:
          example-1:
            description: Default Example
            value: !include examples/historic_uk_fhl_period_summary_create/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.