is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBusinessId
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: List Property Income and Expenses Period Summaries [test only]
description: This endpoint allows the developer to list the submission periods associated with their UK property business for either or both of Furnished Holiday Letting (FHL) and Non FHL UK property or foreign property business for either or both of Furnished Holiday Letting (FHL) in the European Economic Area (EEA) and all other Foreign Property submissions. A National Insurance number, tax year and business ID are required.
(annotations.sandboxData): !include scenarios/default_and_not_found_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/list_property_period_summaries/response.json
        example: !include examples/list_property_period_summaries/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.