is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatBusinessId
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTypeOfBusinessIncorrect
  - errors.ruleBuildingNameNumber
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Retrieve a UK property business annual submission
description: This endpoint allows a developer to retrieve adjustments and allowances for a UK property business. For either or both of Furnished Holiday Letting (FHL) in the European Economic Area (EEA) and Non FHL UK property submissions. A National Insurance number, business ID and tax year are required.
(annotations.sandboxData): !include scenarios/uk_property_annual_submission_retrieve_scenarios.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include schemas/uk_property_annual_submission_retrieve/response.json
        examples:
          example-1:
            description: Example response
            value: !include examples/uk_property_annual_submission_retrieve/response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.