#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: The matching resource is not found.
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  submissionIdNotFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              submissionIdNotFound:
                description: A submission with this Submission ID does not exist for this Business Income Source.
                value:
                  code: SUBMISSION_ID_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: The format of the supplied NINO field is not valid.
                value:
                  code: FORMAT_NINO
  formatBusinessId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatBusinessId:
                description: The format of the supplied Business ID field is not valid.
                value:
                  code: FORMAT_BUSINESS_ID
  formatSubmissionId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSubmissionId:
                description: The format of the supplied Submission ID field is not valid.
                value:
                  code: FORMAT_SUBMISSION_ID
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year field is not valid.
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: An empty or non-matching body was submitted.
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  formatCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCountryCode:
                description: The format of the supplied Country Code field is not valid.
                value:
                  code: FORMAT_COUNTRY_CODE
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: The format of one or more monetary fields is not valid.
                value:
                  code: FORMAT_VALUE
  bothExpensesSupplied:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              bothExpensesSupplied:
                description: Both Expenses and Consolidated Expenses can not be present at the same time.
                value:
                  code: RULE_BOTH_EXPENSES_SUPPLIED