#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

types:
  Type:
    enum: [info,warning,error]

traits:
  fromDate:
    queryParameters:
      fromDate:
        description: 'The start date of the search period. It must be in the form YYYY-MM-DD. If not provided will default to the current tax year start date.'
        example: "2020-04-06"
        required: false
  toDate:
    queryParameters:
      toDate:
        description: "The end date of the search period. It must be in the form YYYY-MM-DD. If not provided will default to the current tax year end date."
        example: "2021-04-05"
        required: false



